packages:
  - packages/*

catalog:
  '@types/node': ^24.0.13
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/coverage-v8': ^4.0.18
  cookie-store: 4.0.0-next.4
  playwright: ^1.53.0
  tsup: ^8.5.0
  vitest: ^4.0.18
