packages:
  - packages/*

catalog:
  '@types/node': ^24.0.13
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  cookie-store: 4.0.0-next.4
  playwright: ^1.53.0
  tsup: ^8.5.0
  vitest: 3.2.4
